<template>
  <div class="lh-base">
    <VueTextSection>
      <template #text>
        <p>
          Thanks a lot for registering to the challenge submission system! In this view, we provide a
          detailed description on how to use the system and describe the overall workflow (see figure
          below).
        </p>
      </template>
      <lightbox-modal class="w-75 mx-auto">
        <img class="img-fluid bg-body-secondary" src="@/assets/images/WorkflowOrganizer.png" alt="" />
      </lightbox-modal>
    </VueTextSection>
    <VueTextSection>
      <template #title>Challenge proposal submission details</template>
      <template #text>
        <p>After filling out at least 90% and all required parameters, you can generate the final proposal
          file. For this, click the “Generate proposal file” button in your proposal view. Afterwards, you will be able
          to
          download your structured challenge design document. Please download the PDF generated by this system and
          upload exact same PDF
          to the <b>Conference Management Toolkit (CMT)</b>.</p>
        <p>
          <b>Note:</b> Uploading a challenge design document that is <i>incomplete</i> or <i>different</i>
          from the one generated with the structured submission system will lead to a <b class="text-danger">desk
            rejection</b> of the challenge.
        </p>
      </template>
    </VueTextSection>
    <VueTextSection>
      <template #title>Challenge review and registration</template>
      <template #text>Your challenge proposal will be reviewed by at least two independent reviewers.
        The reviewers will review the proposal and write their comments via CMT system. Their feedback will be
        forwarded to the MICCAI challenge (co-)chairs who will take the first decision. The feedback
        will result in one of the following outcomes:</template>
      <ul>
        <li>
          <span class="text-danger">Reject</span>: Unfortunately, your proposal was rejected. As the
          number of submitted challenges is increasing every year, it is not possible to accept every
          challenge proposal (see section selection criteria in the main view and 7 reasons why
          challenges were rejected). Depending on your topic, it may be
          possible to merge your proposal with another challenge. The MICCAI challenge (co-)chairs
          will come back to you if this is a viable alternative.
        </li>
        <li>
          <span class="text-warning">Minor/major revision required:</span> Please read the feedback of
          the reviewers and incorporate the feedback in your challenge design. This contains two
          steps:
          <ol>
            <li>Rebuttal: The rebuttal will be written in CMT.</li>
            <li>
              Revision: The document will be revised in the challenge submission system. To do so, go
              back to the submission system and open the respective challenge proposal within the
              proposals view. Revise your challenge proposal according to the reviewer's feedback.
              Please indicate all changes in your rebuttal. Afterwards, go back to the all drafts tab
              to submit your proposal again (see description above). After submission, the revised
              proposal will be uploaded in CMT. The area chairs will check your revision
              and rebuttal
              and will inform you about their final decision.
            </li>
          </ol>
        </li>
        <li>
          <span class="text-success">Accept - revision required later:</span> Congratulations! Your
          challenge proposal has been accepted. But a few revisions are still required. Please have a
          look at the feedback provided by the MICCAI challenge (co-)chairs and reviewers in CMT.
          Afterwards, go back to the challenge submission system, open the respective proposal and
          update your parameters. Finally, submit the challenge again (see above).
        </li>
        <li>
          <span class="text-success">Accept:</span>
          Congratulations! Your challenge proposal has been accepted. To guarantee its execution at
          MICCAI, challenge organizers have to agree to the terms and agreements that will be sent to
          you after notification of acceptance. Furthermore, as described in the about view, challenge
          proposals will be registered, i.e. uploaded online to increase quality control. The MICCAI challenge
          (co-)chairs will mark your challenge as registered soon. Your challenge is now listed as a registered
          challenge
          under tis link: <a
            href="http://www.miccai.org/special-interest-groups/challenges/miccai-registered-challenges/"
            target="_blank">http://www.miccai.org/special-interest-groups/challenges/miccai-registered-challenges/</a>
          <span class="text-success">
            If you have to change any part of your challenge proposal (e.g. evaluation metrics or
            number of data), you have to report those changes to a MICCAI challenge (co-)chair and
            update the challenge within the submission system. Please come back to the submission
            system, open the proposals view and open the options for the respective proposal. Press
            modify proposal. It is now possible to open the proposal and adapt it like you want. Any
            changes will be highlighted in red in the pdf version. After finishing and saving all
            changes, go back to the all drafts view, click options and submit the proposal again. A
            MICCAI challenge (co-)chair will check the changes and upload the new (modified) pdf
            version (see figure below).</span>
        </li>
      </ul>
    </VueTextSection>
    <VueTextSection>
      <template #title> Your challenge is accepted and registered but you have changes? </template>
      <lightbox-modal>
        <img class="img-fluid bg-body-secondary" src="@/assets/images/ModifyRegisteredChallenge.png" alt="" />
      </lightbox-modal>
    </VueTextSection>
    <!-- <VueTextSection>
      <template #title>Parameter categories</template>
      <template #text>
        <p>
          The challenge design parameters are grouped into several categories. First, information has
          to be provided related to the challenge top level. A challenge may contain multiple tasks,
          whose participating teams may vary and for which separate rankings are generated. More
          detailed information is required for each challenge task.
        </p>
        <p>
          General information related to the challenge contains the basic information on your challenge
          such as the title and abstract. The section Further information contains the overall
          planning of your challenge on the day of the conference, like the duration of the challenge
          or the space and hardware requirements.
        </p>
        <p>
          For each task, a summary should be given. More detailed information on the whole challenge
          organization and the participation conditions should be provided. The mission of the
          challenge states the biomedical application of the task, the task categories, imaging
          modalities etc. This is followed by an in-depth description of the tasks' data sets.
          Finally, the evaluation and assessment method of the task should be described.
        </p>
      </template>
      <div class="bg-dark p-3 w-75">
        <lightbox-modal>
          <img class="img-fluid" src="@/assets/images/FormCategories.png" alt="" />
        </lightbox-modal>
      </div>
    </VueTextSection> -->
  </div>
</template>

<script>
import VueTextSection from '@/components/VueTextSection.vue'
import LightboxModal from '@/components/LightboxModal.vue'

export default {
  name: 'WorkflowPage',
  components: { LightboxModal, VueTextSection },
}
</script>

<style scoped></style>
