"""empty message

Revision ID: 4117794b110f
Revises: 2600256f9595
Create Date: 2024-03-15 12:16:41.450698

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4117794b110f"
down_revision = "2600256f9595"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "challenges",
        sa.Column("challenge_is_lighthouse_challenge", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "challenges",
        sa.Column(
            "challenge_lighthouse_general_terms_agreed", sa.Boolean(), nullable=True
        ),
    )
    op.add_column(
        "challenges",
        sa.Column("challenge_lighthouse_what_is_different", sa.String(), nullable=True),
    )
    op.add_column(
        "challenges",
        sa.Column("challenge_lighthouse_closest_challenge", sa.String(), nullable=True),
    )
    op.add_column(
        "challenges",
        sa.Column(
            "challenge_lighthouse_test_set_already_used", sa.String(), nullable=True
        ),
    )
    op.add_column(
        "challenges",
        sa.Column(
            "challenge_lighthouse_clinical_affiliation", sa.String(), nullable=True
        ),
    )
    op.add_column(
        "challenges",
        sa.Column("challenge_lighthouse_deadline_for_data", sa.String(), nullable=True),
    )
    op.add_column(
        "challenges",
        sa.Column(
            "challenge_lighthouse_compute_per_participant", sa.String(), nullable=True
        ),
    )
    op.add_column(
        "conferences", sa.Column("is_lighthouse_challenge", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "conferences", sa.Column("is_open_for_submissions", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "conferences",
        sa.Column("message_before_generate_proposal", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conferences", "message_before_generate_proposal")
    op.drop_column("conferences", "is_open_for_submissions")
    op.drop_column("conferences", "is_lighthouse_challenge")
    op.drop_column("challenges", "challenge_lighthouse_compute_per_participant")
    op.drop_column("challenges", "challenge_lighthouse_deadline_for_data")
    op.drop_column("challenges", "challenge_lighthouse_clinical_affiliation")
    op.drop_column("challenges", "challenge_lighthouse_test_set_already_used")
    op.drop_column("challenges", "challenge_lighthouse_closest_challenge")
    op.drop_column("challenges", "challenge_lighthouse_what_is_different")
    op.drop_column("challenges", "challenge_lighthouse_general_terms_agreed")
    op.drop_column("challenges", "challenge_is_lighthouse_challenge")
    # ### end Alembic commands ###
