"""empty message

Revision ID: 4ad25203924f
Revises: 48fc5a4e1357
Create Date: 2024-10-16 11:13:28.958250

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ad25203924f"
down_revision = "48fc5a4e1357"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "challenges",
        sa.Column("challenge_application_scenarios", sa.String(), nullable=True),
    )
    op.add_column(
        "challenges",
        sa.Column("challenge_duration_explanation", sa.String(), nullable=True),
    )
    op.add_column(
        "challenges", sa.Column("challenge_novelty", sa.String(), nullable=True)
    )
    op.add_column("tasks", sa.Column("task_new_data", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "task_new_data")
    op.drop_column("challenges", "challenge_novelty")
    op.drop_column("challenges", "challenge_duration_explanation")
    op.drop_column("challenges", "challenge_application_scenarios")
    # ### end Alembic commands ###
