"""empty message

Revision ID: 48fc5a4e1357
Revises: 4117794b110f
Create Date: 2024-03-25 14:52:40.062108

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "48fc5a4e1357"
down_revision = "4117794b110f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "challenges",
        sa.Column(
            "challenge_lighthouse_major_scientific_advances", sa.String(), nullable=True
        ),
    )
    op.add_column(
        "challenges",
        sa.Column("challenge_lighthouse_prize_money", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("challenges", "challenge_lighthouse_prize_money")
    op.drop_column("challenges", "challenge_lighthouse_major_scientific_advances")
    # ### end Alembic commands ###
