"""empty message

Revision ID: eaf0735601ce
Revises: bc8ab21b46c0
Create Date: 2025-12-12 11:01:42.541891

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eaf0735601ce"
down_revision = "bc8ab21b46c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("task_platform_sharing_information", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("task_platform_sharing_information")

    # ### end Alembic commands ###
