"""empty message

Revision ID: 083b478727c9
Revises: bc5f58cb1896
Create Date: 2025-02-03 16:54:54.825455

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "083b478727c9"
down_revision = "bc5f58cb1896"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_allowed_for_further_editing", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.drop_column("is_allowed_for_further_editing")

    # ### end Alembic commands ###
