"""empty message

Revision ID: bc8ab21b46c0
Revises: 083b478727c9
Create Date: 2025-11-30 16:13:30.803191

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc8ab21b46c0"
down_revision = "083b478727c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.add_column(sa.Column("challenge_lncs_proceedings", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("challenge_esr_collaboration", sa.String(), nullable=True))

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("task_quantity_of_data", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("task_organizing_team_clinicians", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("task_statistical_analyses_overview", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "task_statistical_analyses_precision_performance_estimates",
                sa.String(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "task_statistical_analyses_performance_variability",
                sa.String(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "task_statistical_analyses_rankings_variability",
                sa.String(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "task_statistical_analyses_test_for_significance",
                sa.String(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "task_statistical_analyses_missing_data_handling",
                sa.String(),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("task_statistical_analyses_software", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("task_statistical_analyses_software")
        batch_op.drop_column("task_statistical_analyses_missing_data_handling")
        batch_op.drop_column("task_statistical_analyses_test_for_significance")
        batch_op.drop_column("task_statistical_analyses_rankings_variability")
        batch_op.drop_column("task_statistical_analyses_performance_variability")
        batch_op.drop_column("task_statistical_analyses_precision_performance_estimates")
        batch_op.drop_column("task_statistical_analyses_overview")
        batch_op.drop_column("task_organizing_team_clinicians")
        batch_op.drop_column("task_quantity_of_data")

    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.drop_column("challenge_esr_collaboration")
        batch_op.drop_column("challenge_lncs_proceedings")

    # ### end Alembic commands ###
